# fly.toml app configuration file generated for hoshizora-cafe-bot on 2023-10-08T02:53:43+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hoshizora-cafe-bot"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
